
default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
        sh "flutter clean"
        sh "flutter build apk --release --target lib/main.dart --no-tree-shake-icons"
        firebase_app_distribution(
        app: "1:876639432571:android:554df8a9ca9f8f1b6d97de",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "
        ahmedalghitany12@gmail.com,
        amanymahmoud22y@gmail.com",
        release_notes: "First Fastlane Firebase Distribution!"
      )
  end

end